/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexion.Mysql;

/**
 *
 * @author Eudy
 */
public class PasoReparacionSeguimiento extends javax.swing.JFrame {

     private Mysql mysql;
     private String estado = "pendiente";
     private String clausula = "";
     private String reparacion_detalle_id = "",usuario_id = "";
     private String nota = "",precioCompleto = "0.00";

    /**
     * Creates new form PasoReparacionSeguimiento
     */
    public PasoReparacionSeguimiento(Mysql mysql) {
        initComponents();
         this.mysql = mysql;
    }
    public void validarSelect(){
        this.estado = this.JCBestado.getSelectedItem().toString();
        this.precioCompleto = this.JTFPrecioFinal.getText();
    }
    
    public void validarEstado(){
        this.validarSelect();
        this.clausula += " estado = '"+this.estado+"', precio_completado = '"+precioCompleto+"' ";
        switch(this.estado){
            case "pendiente":
               this.clausula += ",nota = '"+nota+"' ";
                break;
             case "procesando":
               this.clausula += ",nota_procesando = '"+nota+"', usuario_id_procesando = '"+usuario_id+"', fecha_procesado = now() ";                
                break;
            case "completado":
                this.clausula += ",nota_completado = '"+nota+"', usuario_id_completado = '"+usuario_id+"', fecha_completado = now() ";                
                break;
            case "incompleto":
                this.clausula += ",nota_incompleto_por = '"+nota+"', usuario_id_incompleto_por = '"+usuario_id+"', fecha_incompleto = now() ";                                
                break;
            case "anulada":
                this.clausula += ",comentario_anulado = '"+nota+"', usuario_id_anulado = '"+usuario_id+"', fecha_anulado = now() ";                                
                break;
        }
    }
    public void actualizarDato(){
        this.validarEstado();
        this.mysql.actulizarDatos("reparacion_detalle",this.clausula, " id = '"+reparacion_detalle_id+"' ");
    }
    
    

















    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBGuardar = new javax.swing.JButton();
        JCBestado = new javax.swing.JComboBox<>();
        JLNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTANota = new javax.swing.JTextArea();
        JTFPrecioFinal = new javax.swing.JTextField();
        JLCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JLPrecio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JLCantidad = new javax.swing.JLabel();
        JLPrecioTotal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBGuardar.setText("Guardar Cambios");
        JBGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBGuardarMouseClicked(evt);
            }
        });
        getContentPane().add(JBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        JCBestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "procesando", "pendiente", "completado", "incompleto", "anulada" }));
        getContentPane().add(JCBestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, 20));

        JLNombre.setText("jLabel1");
        getContentPane().add(JLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        JTANota.setColumns(20);
        JTANota.setRows(5);
        jScrollPane1.setViewportView(JTANota);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 420, -1));

        JTFPrecioFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPrecioFinalActionPerformed(evt);
            }
        });
        getContentPane().add(JTFPrecioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, 20));

        JLCodigo.setText("jLabel2");
        getContentPane().add(JLCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel3.setText("NOMBRE ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel4.setText("CODIGO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        JLPrecio.setText("jLabel5");
        getContentPane().add(JLPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel6.setText("PRECIO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel7.setText("ESTADO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, 10));

        jLabel8.setText("PRECIO FINAL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 10));

        jLabel9.setText("COMENTARIO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel10.setText("CANTIDAD");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        JLCantidad.setText("jLabel11");
        getContentPane().add(JLCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        JLPrecioTotal.setText("PRECIO TOTAL");
        getContentPane().add(JLPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel13.setText("PRECIO TOTAL");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFPrecioFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPrecioFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPrecioFinalActionPerformed

    private void JBGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBGuardarMouseClicked
        // TODO add your handling code here:
        this.actualizarDato();
    }//GEN-LAST:event_JBGuardarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBGuardar;
    private javax.swing.JComboBox<String> JCBestado;
    private javax.swing.JLabel JLCantidad;
    private javax.swing.JLabel JLCodigo;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JLabel JLPrecio;
    private javax.swing.JLabel JLPrecioTotal;
    private javax.swing.JTextArea JTANota;
    private javax.swing.JTextField JTFPrecioFinal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
